yum install -y openssl-devel
yum install -y wget
yum install -y libaio-devel
yum install -y gettext
yum install -y make
yum install -y gcc
yum install -y readline-devel
yum install -y yum-utils
yum install -y patch
yum install -y libxml2-devel
yum install -y libxslt-devel
yum install -y rpm-build
yum install -y gd-devel
yum install -y perl-ExtUtils-Embed
yum install -y pcre-devel
yum install -y nginx-${NGINX_MAJOR_VERSION}.${NGINX_MINOR_VERSION}.${NGINX_BUILD_VERSION}